-- AlterTable
ALTER TABLE `Order` ADD COLUMN `payment` ENUM('LINE_PAY') NOT NULL DEFAULT 'LINE_PAY',
    ADD COLUMN `transactionId` VARCHAR(191) NULL,
    ADD COLUMN `transactionStatus` ENUM('PENDING', 'FAILED', 'SUCCESS') NOT NULL DEFAULT 'PENDING';
